version: '2.3'

services:
  pd0:
    image: pingcap/pd:v3.0.2
    ports:
      - "2379:2379"
    volumes:
      - ./config/pd.toml:/pd.toml:ro
      - ./data:/data
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380
      - --data-dir=/data/pd0
      - --config=/pd.toml
    restart: on-failure
  tikv0:
    image: pingcap/tikv:v3.0.2
    ports:
      - "20160:20160"
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv0:20160
      - --data-dir=/data/tikv0
      - --pd=pd0:2379
      - --config=/tikv.toml
    depends_on:
      - "pd0"
    restart: on-failure
  tidb:
    image: pingcap/tidb:v3.0.2
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
    command:
      - --store=tikv
      - --path=pd0:2379
      - --config=/tidb.toml
      - -L=warn
    depends_on:
      - "tikv0"
    restart: on-failure
