log-file = "/home/jenkins/agent/workspace/tispark_ghpr_integration_test/tiflash/tiflash_tikv.log"

[rocksdb]
wal-dir = ""

[security]
ca-path = ""
cert-path = ""
key-path = ""

[server]
addr = "0.0.0.0:20170"
advertise-addr = "127.0.0.1:20170"
engine-addr = "127.0.0.1:3930"
status-addr = "127.0.0.1:20292"

[storage]
data-dir = "/home/jenkins/agent/workspace/tispark_ghpr_integration_test/tiflash/flash"

[raftstore]
# set store capacity, if no set, use disk capacity.
capacity = "8G"